/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.rflournoy.newsreaderwithfrag;

public final class R {
    public static final class array {
        public static final int androidcolors=0x7f040000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int black=0x7f050000;
        public static final int blue=0x7f050001;
        public static final int bluegrey=0x7f050002;
        public static final int darkblue=0x7f050003;
        public static final int darkgreen=0x7f050004;
        public static final int darkorange=0x7f050005;
        public static final int darkpurple=0x7f050006;
        public static final int darkred=0x7f050007;
        public static final int green=0x7f050008;
        public static final int grey=0x7f050009;
        public static final int lightblue=0x7f05000a;
        public static final int lighterblue=0x7f05000b;
        public static final int orange=0x7f05000c;
        public static final int purple=0x7f05000d;
        public static final int red=0x7f05000e;
        public static final int white=0x7f05000f;
    }
    public static final class id {
        public static final int descriptionTextView=0x7f090004;
        public static final int fragment=0x7f090001;
        public static final int fragment2=0x7f090000;
        public static final int itemsListView=0x7f090006;
        public static final int linkTextView=0x7f090005;
        public static final int menu_settings=0x7f090007;
        public static final int pubDateTextView=0x7f090003;
        public static final int titleTextView=0x7f090002;
    }
    public static final class layout {
        public static final int activity_item=0x7f030000;
        public static final int activity_items=0x7f030001;
        public static final int fragment_item=0x7f030002;
        public static final int fragment_items=0x7f030003;
        public static final int listview_item=0x7f030004;
    }
    public static final class menu {
        public static final int activity_item_2=0x7f080000;
        public static final int activity_items=0x7f080001;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
        public static final int hello_blank_fragment=0x7f060001;
        public static final int item_description=0x7f060002;
        public static final int item_link=0x7f060003;
        public static final int item_pub_date=0x7f060004;
        public static final int item_title=0x7f060005;
        public static final int items_title=0x7f060006;
        public static final int loading=0x7f060007;
        public static final int menu_refresh=0x7f060008;
        public static final int menu_settings=0x7f060009;
    }
    public static final class style {
        /** 
            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f070000;
        public static final int AppTheme=0x7f070001;
    }
}
